# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1000/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1000/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jopi/Desktop/aocpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jopi/Desktop/aocpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1000/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1000/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jopi/Desktop/aocpp/CMakeFiles /home/jopi/Desktop/aocpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jopi/Desktop/aocpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/jopi/Desktop/aocpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ArgentumOnline

# Build rule for target.
ArgentumOnline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ArgentumOnline
.PHONY : ArgentumOnline

# fast build rule for target.
ArgentumOnline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/build
.PHONY : ArgentumOnline/fast

source/audio.o: source/audio.cpp.o
.PHONY : source/audio.o

# target to build an object file
source/audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/audio.cpp.o
.PHONY : source/audio.cpp.o

source/audio.i: source/audio.cpp.i
.PHONY : source/audio.i

# target to preprocess a source file
source/audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/audio.cpp.i
.PHONY : source/audio.cpp.i

source/audio.s: source/audio.cpp.s
.PHONY : source/audio.s

# target to generate assembly for a file
source/audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/audio.cpp.s
.PHONY : source/audio.cpp.s

source/engine.o: source/engine.cpp.o
.PHONY : source/engine.o

# target to build an object file
source/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/engine.cpp.o
.PHONY : source/engine.cpp.o

source/engine.i: source/engine.cpp.i
.PHONY : source/engine.i

# target to preprocess a source file
source/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/engine.cpp.i
.PHONY : source/engine.cpp.i

source/engine.s: source/engine.cpp.s
.PHONY : source/engine.s

# target to generate assembly for a file
source/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/engine.cpp.s
.PHONY : source/engine.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/resources.o: source/resources.cpp.o
.PHONY : source/resources.o

# target to build an object file
source/resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/resources.cpp.o
.PHONY : source/resources.cpp.o

source/resources.i: source/resources.cpp.i
.PHONY : source/resources.i

# target to preprocess a source file
source/resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/resources.cpp.i
.PHONY : source/resources.cpp.i

source/resources.s: source/resources.cpp.s
.PHONY : source/resources.s

# target to generate assembly for a file
source/resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/resources.cpp.s
.PHONY : source/resources.cpp.s

source/surface.o: source/surface.cpp.o
.PHONY : source/surface.o

# target to build an object file
source/surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/surface.cpp.o
.PHONY : source/surface.cpp.o

source/surface.i: source/surface.cpp.i
.PHONY : source/surface.i

# target to preprocess a source file
source/surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/surface.cpp.i
.PHONY : source/surface.cpp.i

source/surface.s: source/surface.cpp.s
.PHONY : source/surface.s

# target to generate assembly for a file
source/surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/surface.cpp.s
.PHONY : source/surface.cpp.s

source/texture.o: source/texture.cpp.o
.PHONY : source/texture.o

# target to build an object file
source/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/texture.cpp.o
.PHONY : source/texture.cpp.o

source/texture.i: source/texture.cpp.i
.PHONY : source/texture.i

# target to preprocess a source file
source/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/texture.cpp.i
.PHONY : source/texture.cpp.i

source/texture.s: source/texture.cpp.s
.PHONY : source/texture.s

# target to generate assembly for a file
source/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/texture.cpp.s
.PHONY : source/texture.cpp.s

source/window.o: source/window.cpp.o
.PHONY : source/window.o

# target to build an object file
source/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/window.cpp.o
.PHONY : source/window.cpp.o

source/window.i: source/window.cpp.i
.PHONY : source/window.i

# target to preprocess a source file
source/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/window.cpp.i
.PHONY : source/window.cpp.i

source/window.s: source/window.cpp.s
.PHONY : source/window.s

# target to generate assembly for a file
source/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArgentumOnline.dir/build.make CMakeFiles/ArgentumOnline.dir/source/window.cpp.s
.PHONY : source/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ArgentumOnline"
	@echo "... source/audio.o"
	@echo "... source/audio.i"
	@echo "... source/audio.s"
	@echo "... source/engine.o"
	@echo "... source/engine.i"
	@echo "... source/engine.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/resources.o"
	@echo "... source/resources.i"
	@echo "... source/resources.s"
	@echo "... source/surface.o"
	@echo "... source/surface.i"
	@echo "... source/surface.s"
	@echo "... source/texture.o"
	@echo "... source/texture.i"
	@echo "... source/texture.s"
	@echo "... source/window.o"
	@echo "... source/window.i"
	@echo "... source/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/jopi/Desktop/aocpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

